#! /bin/bash
#  gather dotfiles in home dir
#  so i dont lose all my shit again
#  ffs

BLUE='\033[0;34m'
WHITE='\033[1;37m'
NC='\033[0m'

echo
echo -e "################### ~ level configs ###################"

echo -e "Copying ${BLUE}.profile${NC}..."
cp $HOME/.profile .

echo -e "Copying ${BLUE}.vimrc${NC}..."
cp $HOME/.vimrc .

echo -e "Copying ${BLUE}.xinitrc${NC}..."
cp $HOME/.xinitrc .

echo -e "Copying ${BLUE}.Xresources${NC}..."
cp $HOME/.Xresources .

echo -e "Copying ${BLUE}.zprofile${NC}..."
cp $HOME/.zprofile .

echo -e "Copying ${BLUE}.zshrc${NC}..."
cp $HOME/.zshrc .

echo -e "#################### .config folders ####################"

echo -e "Copying ${BLUE}bspwm${NC}..."
cp -r $HOME/.config/bspwm/ ./.config

echo -e "Copying ${BLUE}cava${NC}..."
cp -r $HOME/.config/cava/ ./.config

echo -e "Copying ${BLUE}mpv${NC}..."
cp -r $HOME/.config/mpv/ ./.config

echo -e "Copying ${BLUE}neofetch${NC}..."
cp -r $HOME/.config/neofetch/ ./.config

echo -e "Copying ${BLUE}polybar${NC}..."
cp -r $HOME/.config/polybar/ ./.config

echo -e "Copying ${BLUE}powerline${NC}..."
cp -r $HOME/.config/powerline/ ./.config

echo -e "Copying ${BLUE}sxhkd${NC}..."
cp -r $HOME/.config/sxhkd/ ./.config

echo -e "######################### other #########################"

echo -e "Copying ${BLUE}homepage${NC}..."
cp -r $HOME/Documents/dev/random/homepage/ ./

###############################################################
echo
echo -e "${WHITE}Done${NC}!"
